### ISSUE TITLE
Grafana

### ISSUE THREAD

**Issue by iron-2** [maglub/rpi-sous-vide#13]
I finally installed your app.
All installation ran fine as far as I can tell.
A question though, when I go to the Grafana tab there is no database selected, should there be one connected from start?
I did not yet set the electronics together, maybe thats why.

Br
Henke

**Comment by maglub** [comment]
Hmmm, there should be a data source there already.

Which installation of Raspbian did you use? The latest and greatest (I have
not tested it on that yet)?

//magnus

**Comment by iron-2** [comment]
I think I did, freshly downloaded from RPI site.

Is there any log I can look in?

**Comment by iron-2** [comment]
I made the connection in grafana. 
Think it's easier once I get a temp. sensor in there

**Comment by maglub** [comment]
I just installed rpi-sous-vide on a 2018-04-18/19 raspbian stretch, without any sensors. This is what I get.

* ./setup.sh - ok
* reboot
* ./setup-influxdb.sh - ok

```
pi@raspberrypi:~/rpi-sous-vide $ influx
Connected to http://localhost:8086 version 1.5.2
InfluxDB shell version: 1.5.2
> show databases;
name: databases
name
----
smoker
```

* ./setup-grafana.sh

```
  - Setting dashboard as home: smoker
./setup-grafana.sh: line 113: syntax error near unexpected token `;;'
./setup-grafana.sh: line 113: `  ;;'
```

I will look into this.

**Comment by maglub** [comment]
The ";;" did not really affect anything, but the installation still did not work properly.

I think it was a weird timing issue. I added a "sleep 3" after deleting (a non existing) dashboard, and now it seems to work better. I have tried both to just do "git pull" and ./setup-grafana.sh without complete reinstall of raspbian stretch lite, and also a new fresh install, and both seems to work now.

Please do a "git pull" and run ./setup-grafana.sh again.

Before you have any data/sensors, you will see some weird sort of data on the dials, and no data on the dashboard.

When you have the sensors installed, don't forget to generate the aliases.

```
cd ~/rpi-sous-vide
./bin/genAliases | tee conf/aliases.conf
```

Sorry for the inconvenience.

**Comment by maglub** [comment]
![image](https://user-images.githubusercontent.com/2961018/39598365-99904ba2-4f18-11e8-9760-e62938162bde.png)

**Comment by maglub** [comment]
Hii again,

It seems like the "issue" was with grafana being very slow to start. I have upped another sleep from 5 seconds to 10 seconds, and I can now consistently install grafana with the proper dashboard.

I also added "dummy data" to the influx installation.

If you would have the time, please try the following:

```
git pull
./setup-influx.sh
./setup-grafana.sh
```

And now you should be able to see a dashboard that is representative of when you have sensors.

**Comment by iron-2** [comment]
Thanks,
I'll try it in this moment. I'll let you know.

Hej Svejs

**Comment by iron-2** [comment]
Thanks,
Now it seems to be working.
Need to put together the equipment.

A side not.
What temperature probes do you use specifically for the smoker. The one I got now is the water proof one, but I don't think it will last long inside the bbq.

**Comment by maglub** [comment]
I have used the water proof one for over a year, and it has survived so far. It looks like it has been through a war, but still going strong.

The temperatures I am using is rarely going over 110 degrees, so it is within "designed specs".

The probes I use cost around a couple of USD a piece, so when it breaks it is not so much of a deal.
